# Setup
title:               Країна Понад Усе
tagline:             Благодійний Фонд
title_en:            Kraina Ponad Yse
tagline_en:          Charitable Foundation
url:                 https://kraina-ponad-yse.com
description:         ''
baseurl:             ''
permalink:           pretty

# About/contact
author:
  name:              Vitalii Elenhaupt
  url:               https://twitter.com/veelenga
  email:             velenhaupt@gmail.com

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
